---
- hosts: ubunutuhosts
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install on ubunutuhost
    apt:
     name: apache2
    state: present

  - name: start the service 
    service:
     name: apache2
    state: present
  - name: i want to copy index file into all nodes
    template:
      src: index.j2
      dest: /var/www/html/index.html