---
# tasks file for mytominstall
- name: install tomcat
  yum:
   name: tomcat
   state: present

- name:  copy tom config file into all nodes
  template:
    src:  templates/mytomconfig.j2
    dest: /usr/share/tomcat/conf/tomcat.conf
  notify: starttomcat

- name:  Install Admin Packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps
- name: coy tom user file into all nodes
  template:
    src: templates/mytomuser.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: restarttomcat
- name: i want to deploy ravi java war file into webapps 
  get_url:
    url: http://18.191.178.51:8081/artifactory/myshiva/1/target/mahaLogin-1.0.war 
    dest: /usr/share/tomcat/webapps/mahaLogin-1.0.war
    force_basic_auth: yes